---
- name: Arithmetic Practice
  hosts: localhost
  gather_facts: no
  vars:
   x: 20
   y: 10

  tasks:
  - debug:
     msg:
     - "The value of x is: {{x}} and type is {{x|type_debug}}"
     - "The value of y is: {{y}} and type is {{y|type_debug}}"

