---
- name: Working with Conditional statement
  hosts: localhost
  gather_facts: no
  
  vars:
   x: 5
   y: 67
   my_list: [5,6,7]

  tasks:
  - debug:
     msg:
     - "the value of x is {{x}} and value of y is {{y}}"
    when: x==y
  
  - debug:
     msg:
     - "x is present in my_list"
    when: x in my_list
