---
- hosts: localhost
  gather_facts: no
  
  vars:
   x: 34
#   pakgs: ['vim','nano','httpd','nginx']
   pakgs:
   - 'vim'
   - 'nano'
   - 'httpd'
   - 'nginx'

#   web_servers: {'Linux':'httpd','ubuntu':'apache2'}
   web_servers:
    'Linux': 'httpd'
    'ubuntu': 'apache'

  tasks:
  - debug: var=web_servers
  - debug: var=web_servers.keys()
  - debug: var=web_servers['Linux']
  - debug: var=web_servers.get('Linux')

