---
- hosts: localhost
  gather_facts: no
  vars:
   x: 20
   my_name: "Dinesh"
  vars_prompt:
   name: y
   prompt: "Enter a value of y"
   private: no
  tasks:
  - debug:
     msg:
     - "The value of x is: {{x}}"
     - "The value of my_name is: {{my_name}}"
     - "The value of y is: {{y}}"
