---
- name: Working with loops
  hosts: localhost
  gather_facts: no
  become: yes
  tasks:
    - name: Installing Packages
      apt:
        name: "{{item}}"
        state: present
      loop:
        - curl
        - wget
        - vim

      
