---
- name: Working with Logical Operators
  hosts: localhost
  gather_facts: no
  
  vars:
   x: 5
   y: 7
   z: [4,5,6]
  
  tasks:
  - debug:
     msg:
     - "The value of x is:{{x}}, The value of y is:{{y}} and value of z is: {{z}}"
     - "x<y and y in z : {{ x<y and y in z }}"
     - "{{ (4<5) and (5>1) and (5>2) and (9==0) }}"
     - "{{ (4<5) or (5>1) or (5>2) or (9==0) }}"
